# practiceing -------
view(BBL_isotope_data1)
plot(d18O, d13C)
ggplot(data = BBL_isotope_data1, mapping = aes(x = dist from CEJ, y = d13C))
plot(5,6)
<- read_excel(BBL_isotope_data1)
plot(x = BBL_isotope_data1$`Dist from CEJ`,y = BBL_isotope_data1$d13C,xlab = "Dist from CEJ", ylab = "d13C")
mean(BBL_isotope_data1$d13C)
t.test(mean(BBL_isotope_data1$d13C))
t.test(-7.904, -13.19714286, paired = TRUE)
view(BBL_isotop_data1)
t.test(BBL_isotope_data_wally$d13C_T1, BBL_isotope_data_wally$d13C_T2, paired = TRUE)
library(assignR)
library(raster)
library(sp)
data("naMap")
plot(naMap)
getIsoscapes(isoType = "USSr")
data("d2h_lrNA")
plot(d2h_lrNA)
data("knownOrig")
names(knownOrig$sites)
names(knownOrig$samples)
names(knownOrig$sources)
plot(assignR:::wrld_simpl)
points(knownOrig$sites, col = "red")
unique(knownOrig$samples$Taxon)
Ll_d = subOrigData(taxon = "Lanius ludovicianus", mask = naMap)
names(BBL_isotope_data_wally)
data("BBL_Sr_grass_sample_data")
names(BBL_Sr_grass_sample_data)
plot(assignR:::wrld_simpl)
points(x = BBL_Sr_grass_sample_data$Latitude, y = BBL_Sr_grass_sample_data$Longitude)
map_data(naMap, region = "southeast")
View(BBL_isotope_data1)

names(BBL_isotope_data1)